databases:
  - name: my-personal-database
    databaseName: my_personal_database_ql43
    user: my_personal_database_ql43_user

services:
  - type: web
    name: full_stack_capstone_back_end
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-personal-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false